### ISSUE TITLE
Doesn't' work on bookmarklets.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Vinne2/bookmark-iconizer#1]
```
What steps will reproduce the problem?

1. Try to change a bookmarklet's icon.
2. It accepts the base64 URL and appears to accept it. 


What is the expected output? What do you see instead?

When you reload the options page and search for the same bookmark(s) it has no 
favicon and the actual bookmarklet on my bookmarks bar has not changed.

What version of the product are you using? On what operating system?
Version: 1.5.1 on MS Windows XP.
```

Original issue reported on code.google.com by `software...@gmail.com` on 1 Dec 2013 at 3:26

Attachments:
- [bookmarklet.png](https://storage.googleapis.com/google-code-attachments/bookmark-iconizer/issue-1/comment-0/bookmarklet.png)

**Comment by Kaligula0** [comment]
I can't quite understand this – I've just set an icon for a bookmarklet, so it works for me.
 On search page bookmarklets will never have icons, because the extension doesn't read them from Chrome's settings/cache but loads favicon from the website's web page. As bookmarklets are not a link to website, the extension cannot read any favicon from the internet, thus it shows text "(JS)".
 BUT the actual boomarklet on the bookmarks bar should already have the favicon you've set. ONLY after you proceed through ALL steps (remember that after each step you have to click [OK] button, so that next step will show up below), including saving the HTM/HTML file and importing it back to Chrome.

I believe you didn't proceed through all steps? :)
Remember that after Chrome removed some permissions for browser extensions user 
has to export the generated file and import it back to Bookmark Manager 
manually.

**Comment by johnyradio** [comment]
this does not work for me, on diigolet
https://www.diigo.com/tools/diigolet

my base64 file, created with your extension, is attached. 
[diigo-iconized.zip](https://github.com/Vinne2/bookmark-iconizer/files/956682/diigo-iconized.zip)

btw, when i imported (using bookmark-manager in SlimJet Chromium-based browser), i could only select "html" files, but your extension exports an "htm" file. So i had to rename your file to "html" before i could import.

**Comment by johnyradio** [comment]
i discovered the fix (for me). 
the base64 must have "data" prefix (or maybe some other issue with the base64 converter i used).

this converter will give the "data" prefix, and works.
https://www.base64-image.de/

**Comment by Kaligula0** [comment]
I version 1.6.0 I added a note that the base64 should start with "data:image/png;base64,iVBORw0KGgoAblahblahblah…". New version should be online shortly. A converters listed under the table in the extension provide proper base64, so I don't know where your problem came from.

**Comment by Kaligula0** [comment]
As for the HTM/HTML issue – the extension can export only using Chrome's native function. And that uses HTM export. Weird, because when importing it looks for HTML files though…
