### ISSUE TITLE
Results in duplicate bookmarks

### ISSUE THREAD

**Issue by johnyradio** [Vinne2/bookmark-iconizer#3]
the old bookmark remains, when the new bookmark is imported. 
they BOTH get iconized. 
it's a minor convenience issue (must manually delete one of them). 

an improvement would be:
- auto-delete the old one
or
- don't import the new bookmark-- just apply the base64 image to the existing bookmark. 

thx!

**Comment by Kaligula0** [comment]
The workaround which is used by the extension consists of few steps, when the last one is to import bookmarks. This happens via Chrome's native function and cannot be changed by an extension. Chrome imports new bookmarks to a folder at the far end of Bookmark bar. This folders name is "Imported" or "Imported bookmarks". You can simply remove that folder (yes, with all your carefully imported bookmarks!) as those bookmarks are only duplicates of your own old bookmarks, which are still in their own old places. But now they're with your new icons ;) (because during importing you teached Chrome which bookmarks should have which icons).

**Comment by Kaligula0** [comment]
The new version of extension can remove that folder. It will be public soon.

**Comment by johnyradio** [comment]
Thanks!
